version: '3.1'

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server_python:
    restart: always
    image: python
    volumes:
      - ./server_python:/server_python
    build:
      context: ./server_python
      dockerfile: ./DockerfilePython
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8000
    depends_on:
      - db
  react:
    image: react
    build:
      context: ./app
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - server_python