version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d
  adminer:
    container_name: adminer
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server_python:
    container_name: server_python
    restart: always
    image: python
    volumes:
      - ./server_python:/server_python
    build:
      context: ./server_python
      dockerfile: ./DockerfilePython
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ADMIN_PASS=${ADMIN_PASS}
    depends_on:
      - db
  react:
    restart: always
    image: react
    container_name: react
    build:
      context: ./app
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=${SERVER_PYTHON_URI}
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - server_python